language: node_js
node_js: "0.10"
install:
  - sudo apt-get install imagemagick
  - sudo apt-get install graphicsmagick
  - npm install
  - npm install -g gulp
  - npm install -g casperjs
before_script:
  - gulp build --cwd=bookmarklet
  - gulp server --cwd=bookmarklet
script: npm test
